packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.15
  '@bufbuild/buf': ^1.65.0
  '@bufbuild/protobuf': ^2.11.0
  '@bufbuild/protoc-gen-es': ^2.11.0
  '@bufbuild/protovalidate': ^1.1.1
  '@commitlint/cli': ^20.4.1
  '@commitlint/config-conventional': ^20.4.1
  '@connectrpc/connect': ^2.1.1
  '@connectrpc/connect-node': ^2.1.1
  '@connectrpc/validate': ^0.2.0
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/api-logs': ^0.54.2
  '@opentelemetry/auto-instrumentations-node': ^0.50.2
  '@opentelemetry/core': ^1.28.0
  '@opentelemetry/exporter-logs-otlp-grpc': ^0.54.2
  '@opentelemetry/exporter-logs-otlp-http': ^0.54.2
  '@opentelemetry/exporter-metrics-otlp-grpc': ^0.54.2
  '@opentelemetry/exporter-metrics-otlp-http': ^0.54.2
  '@opentelemetry/exporter-trace-otlp-grpc': ^0.54.2
  '@opentelemetry/exporter-trace-otlp-http': ^0.54.2
  '@opentelemetry/instrumentation': ^0.54.2
  '@opentelemetry/resource-detector-container': ^0.4.1
  '@opentelemetry/resources': ^1.30.1
  '@opentelemetry/sdk-logs': ^0.54.2
  '@opentelemetry/sdk-metrics': ^1.30.1
  '@opentelemetry/sdk-node': ^0.54.2
  '@opentelemetry/sdk-trace-node': ^1.30.1
  '@opentelemetry/semantic-conventions': ^1.39.0
  c8: ^10.1.3
  env-var: ^7.5.0
  husky: ^9.1.7
  typescript: ^5.9.3
  zod: ^3.25.76

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@bufbuild/buf'
  - protobufjs
