/**
 * protoc-gen-connectum-catalog — Buf/protoc plugin.
 *
 * Emits one `catalog.gen.ts` per buf module containing:
 * - a runtime `serviceCatalog` object keyed by proto `typeName`;
 * - module augmentation of `@connectum/core`'s `ConnectumCallMap` (unary
 *   methods) and `ConnectumStreamMap` (streaming methods), which is what types
 *   `ctx.call` / `ctx.stream`.
 *
 * The generated file is self-contained: it imports each service descriptor and
 * message shape from the protobuf-es output with `.js`-extension relative
 * specifiers, and carries the mandatory `import type {} from "@connectum/core";`
 * so the augmentation resolves in cross-package builds (TS2664 otherwise).
 *
 * @module plugin
 */

import type { DescService } from "@bufbuild/protobuf";
import { createEcmaScriptPlugin, type Schema } from "@bufbuild/protoplugin";

/** Self-reported plugin version (appears in the generated preamble). */
const PLUGIN_VERSION = "1.0.0-rc.11";

/** proto streaming `methodKind` → Connectum `ConnectumStreamMap` kind discriminator. */
const STREAM_KIND = {
    server_streaming: "server-stream",
    client_streaming: "client-stream",
    bidi_streaming: "bidi",
} as const;

/** Options parsed from the plugin parameter string. */
interface CatalogOptions {
    /** Output file name, relative to the output root. Default `catalog.gen.ts`. */
    readonly outputFile: string;
}

/** Matches Windows absolute paths: drive-letter (`C:\`, `C:/`) and UNC (`\\server\share`). */
const WINDOWS_ABSOLUTE = /^[A-Za-z]:[\\/]|^\\\\/;

/**
 * Parse `output_file=...` (the only supported option). Rejects empty, absolute
 * (POSIX and Windows), and parent-traversal paths so generation cannot escape
 * the output root.
 */
function parseCatalogOptions(rawOptions: { key: string; value: string }[]): CatalogOptions {
    let outputFile = "catalog.gen.ts";
    for (const { key, value } of rawOptions) {
        if (key !== "output_file") {
            throw new Error(`protoc-gen-connectum-catalog: unknown option "${key}".`);
        }
        if (value.length === 0) {
            throw new Error("protoc-gen-connectum-catalog: output_file must not be empty.");
        }
        if (value.startsWith("/") || WINDOWS_ABSOLUTE.test(value) || value.split(/[/\\]/).includes("..")) {
            throw new Error(`protoc-gen-connectum-catalog: output_file must be a relative path inside the output root (got "${value}").`);
        }
        outputFile = value;
    }
    return { outputFile };
}

/** All services in the files-to-generate, in declaration order. */
function servicesToGenerate(schema: Schema<CatalogOptions>): DescService[] {
    return schema.files.flatMap((file) => file.services);
}

/** Generate the aggregated `catalog.gen.ts` for the buf module. */
function generateCatalog(schema: Schema<CatalogOptions>): void {
    const services = servicesToGenerate(schema);
    const f = schema.generateFile(schema.options.outputFile);

    f.print`// @generated by protoc-gen-connectum-catalog v${PLUGIN_VERSION}. DO NOT EDIT.`;
    // MANDATORY (polyrepo F1 / TS2664): forces @connectum/core to load so the
    // module augmentation below merges in cross-package consumers.
    f.print`import type {} from "@connectum/core";`;
    f.print``;

    if (services.length === 0) {
        // Empty input is not a hard failure (incremental buf workflow): emit a
        // valid, augmentation-free catalog and warn on stderr.
        process.stderr.write("protoc-gen-connectum-catalog: no services in files-to-generate; emitted an empty catalog.\n");
        f.print(f.export("const", "serviceCatalog"), " = Object.freeze({});");
        return;
    }

    f.print(f.export("const", "serviceCatalog"), " = {");
    for (const service of services) {
        f.print`    "${service.typeName}": ${f.importSchema(service)},`;
    }
    f.print`} as const;`;
    f.print``;

    f.print`declare module "@connectum/core" {`;
    f.print`    interface ConnectumCallMap {`;
    for (const service of services) {
        for (const method of service.methods) {
            if (method.methodKind !== "unary") continue;
            f.print`        "${service.typeName}/${method.name}": { request: ${f.importShape(method.input)}; response: ${f.importShape(method.output)} };`;
        }
    }
    f.print`    }`;
    f.print`    interface ConnectumStreamMap {`;
    for (const service of services) {
        for (const method of service.methods) {
            if (method.methodKind === "unary") continue;
            const kind = STREAM_KIND[method.methodKind];
            f.print`        "${service.typeName}/${method.name}": { request: ${f.importShape(method.input)}; response: ${f.importShape(method.output)}; kind: "${kind}" };`;
        }
    }
    f.print`    }`;
    f.print`}`;
}

/** The protoc-gen-connectum-catalog plugin. */
export const protocGenCatalog = createEcmaScriptPlugin({
    name: "protoc-gen-connectum-catalog",
    version: `v${PLUGIN_VERSION}`,
    parseOptions: parseCatalogOptions,
    generateTs: generateCatalog,
});
