// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=.ts,erasable_syntax=true"
// @generated from file fixture/v1/common.proto (package fixture.v1, syntax proto3)
/* eslint-disable */

import type { Message, UnknownEnum } from "@bufbuild/protobuf";
import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file fixture/v1/common.proto.
 */
export const file_fixture_v1_common: GenFile =
    /*@__PURE__*/
    fileDesc(
        "ChdmaXh0dXJlL3YxL2NvbW1vbi5wcm90bxIKZml4dHVyZS52MSLFAgoETWV0YRIrCgdjcmVhdGVkGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIsCgZsYWJlbHMYAiADKAsyHC5maXh0dXJlLnYxLk1ldGEuTGFiZWxzRW50cnkSIAoFbGV2ZWwYAyABKA4yES5maXh0dXJlLnYxLkxldmVsEiUKBXN0YXRlGAQgASgOMhYuZml4dHVyZS52MS5NZXRhLlN0YXRlEiQKBW5vdGVzGAUgAygLMhUuZml4dHVyZS52MS5NZXRhLk5vdGUaFAoETm90ZRIMCgR0ZXh0GAEgASgJGi0KC0xhYmVsc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiLgoFU3RhdGUSFQoRU1RBVEVfVU5TUEVDSUZJRUQQABIOCgpTVEFURV9PUEVOEAEqLgoFTGV2ZWwSFQoRTEVWRUxfVU5TUEVDSUZJRUQQABIOCgpMRVZFTF9ISUdIEAEySgoQVW5tb3VudGVkU2VydmljZRI2CgROb29wEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5YgZwcm90bzM",
        [file_google_protobuf_empty, file_google_protobuf_timestamp],
    );

/**
 * @generated from message fixture.v1.Meta
 */
export type Meta = Message<"fixture.v1.Meta"> & {
    /**
     * @generated from field: google.protobuf.Timestamp created = 1;
     */
    created?: Timestamp | undefined;

    /**
     * Synthesizes the map-entry message fixture.v1.Meta.LabelsEntry.
     *
     * @generated from field: map<string, string> labels = 2;
     */
    labels: { [key: string]: string };

    /**
     * @generated from field: fixture.v1.Level level = 3;
     */
    level: Level;

    /**
     * @generated from field: fixture.v1.Meta.State state = 4;
     */
    state: Meta_State;

    /**
     * @generated from field: repeated fixture.v1.Meta.Note notes = 5;
     */
    notes: Meta_Note[];
};

/**
 * Describes the message fixture.v1.Meta.
 * Use `create(MetaSchema)` to create a new message.
 */
export const MetaSchema: GenMessage<Meta> = /*@__PURE__*/ messageDesc(file_fixture_v1_common, 0);

/**
 * @generated from message fixture.v1.Meta.Note
 */
export type Meta_Note = Message<"fixture.v1.Meta.Note"> & {
    /**
     * @generated from field: string text = 1;
     */
    text: string;
};

/**
 * Describes the message fixture.v1.Meta.Note.
 * Use `create(Meta_NoteSchema)` to create a new message.
 */
export const Meta_NoteSchema: GenMessage<Meta_Note> = /*@__PURE__*/ messageDesc(file_fixture_v1_common, 0, 0);

/**
 * Nested enum: its values live in the message scope (fixture.v1.Meta.STATE_OPEN).
 *
 * @generated from enum fixture.v1.Meta.State
 */
export const Meta_State = {
    /**
     * @generated from enum value: STATE_UNSPECIFIED = 0;
     */
    UNSPECIFIED: 0,

    /**
     * @generated from enum value: STATE_OPEN = 1;
     */
    OPEN: 1,
} as const;

/**
 * Nested enum: its values live in the message scope (fixture.v1.Meta.STATE_OPEN).
 *
 * @generated from enum fixture.v1.Meta.State
 */
export type Meta_State = (typeof Meta_State)[keyof typeof Meta_State] | UnknownEnum;

/**
 * Describes the enum fixture.v1.Meta.State.
 */
export const Meta_StateSchema: GenEnum<Meta_State> = /*@__PURE__*/ enumDesc(file_fixture_v1_common, 0, 0);

/**
 * Top-level enum: its values live in the package scope (fixture.v1.LEVEL_HIGH).
 *
 * @generated from enum fixture.v1.Level
 */
export const Level = {
    /**
     * @generated from enum value: LEVEL_UNSPECIFIED = 0;
     */
    UNSPECIFIED: 0,

    /**
     * @generated from enum value: LEVEL_HIGH = 1;
     */
    HIGH: 1,
} as const;

/**
 * Top-level enum: its values live in the package scope (fixture.v1.LEVEL_HIGH).
 *
 * @generated from enum fixture.v1.Level
 */
export type Level = (typeof Level)[keyof typeof Level] | UnknownEnum;

/**
 * Describes the enum fixture.v1.Level.
 */
export const LevelSchema: GenEnum<Level> = /*@__PURE__*/ enumDesc(file_fixture_v1_common, 0);

/**
 * Declared in an imported file but never mounted: reflection must not list it.
 *
 * @generated from service fixture.v1.UnmountedService
 */
export const UnmountedService: GenService<{
    /**
     * @generated from rpc fixture.v1.UnmountedService.Noop
     */
    noop: {
        methodKind: "unary";
        input: typeof EmptySchema;
        output: typeof EmptySchema;
    };
}> = /*@__PURE__*/ serviceDesc(file_fixture_v1_common, 0);
