// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=.ts,erasable_syntax=true"
// @generated from file fixture/v1/legacy.proto (package fixture.v1, syntax proto2)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file fixture/v1/legacy.proto.
 */
export const file_fixture_v1_legacy: GenFile =
    /*@__PURE__*/
    fileDesc(
        "ChdmaXh0dXJlL3YxL2xlZ2FjeS5wcm90bxIKZml4dHVyZS52MSIfCgpFeHRlbmRhYmxlEgoKAmlkGAEgASgJKgUIZBDIASI+CgVTY29wZTI1CgpuZXN0ZWRfZXh0EhYuZml4dHVyZS52MS5FeHRlbmRhYmxlGGUgASgJUgluZXN0ZWRFeHQ6LwoHdG9wX2V4dBIWLmZpeHR1cmUudjEuRXh0ZW5kYWJsZRhkIAEoBVIGdG9wRXh0",
    );

/**
 * @generated from message fixture.v1.Extendable
 */
export type Extendable = Message<"fixture.v1.Extendable"> & {
    /**
     * @generated from field: optional string id = 1;
     */
    id: string;
};

/**
 * Describes the message fixture.v1.Extendable.
 * Use `create(ExtendableSchema)` to create a new message.
 */
export const ExtendableSchema: GenMessage<Extendable> = /*@__PURE__*/ messageDesc(file_fixture_v1_legacy, 0);

/**
 * @generated from message fixture.v1.Scope
 */
export type Scope = Message<"fixture.v1.Scope"> & {};

/**
 * Describes the message fixture.v1.Scope.
 * Use `create(ScopeSchema)` to create a new message.
 */
export const ScopeSchema: GenMessage<Scope> = /*@__PURE__*/ messageDesc(file_fixture_v1_legacy, 1);

/**
 * @generated from extension: optional string nested_ext = 101;
 */
export const Scope_nested_ext: GenExtension<Extendable, string> = /*@__PURE__*/ extDesc(file_fixture_v1_legacy, 1, 0);

/**
 * @generated from extension: optional int32 top_ext = 100;
 */
export const top_ext: GenExtension<Extendable, number> = /*@__PURE__*/ extDesc(file_fixture_v1_legacy, 0);
