// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=.ts,erasable_syntax=true"
// @generated from file fixture/v1/multi.proto (package fixture.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file fixture/v1/multi.proto.
 */
export const file_fixture_v1_multi: GenFile =
    /*@__PURE__*/
    fileDesc(
        "ChZmaXh0dXJlL3YxL211bHRpLnByb3RvEgpmaXh0dXJlLnYxMkgKDk1vdW50ZWRTZXJ2aWNlEjYKBFBpbmcSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkyigEKFFVubW91bnRlZFBlZXJTZXJ2aWNlEjYKBFBpbmcSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSOgoEQ2hhdBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSgBMAFiBnByb3RvMw",
        [file_google_protobuf_empty],
    );

/**
 * Two services in one file. Tests mount only MountedService: protocols and
 * startup checks must consider the services actually mounted, not every
 * service of a mounted file. The unmounted one carries a bidi method so a
 * transport check that walks the whole file would flag it.
 *
 * @generated from service fixture.v1.MountedService
 */
export const MountedService: GenService<{
    /**
     * @generated from rpc fixture.v1.MountedService.Ping
     */
    ping: {
        methodKind: "unary";
        input: typeof EmptySchema;
        output: typeof EmptySchema;
    };
}> = /*@__PURE__*/ serviceDesc(file_fixture_v1_multi, 0);

/**
 * @generated from service fixture.v1.UnmountedPeerService
 */
export const UnmountedPeerService: GenService<{
    /**
     * @generated from rpc fixture.v1.UnmountedPeerService.Ping
     */
    ping: {
        methodKind: "unary";
        input: typeof EmptySchema;
        output: typeof EmptySchema;
    };
    /**
     * @generated from rpc fixture.v1.UnmountedPeerService.Chat
     */
    chat: {
        methodKind: "bidi_streaming";
        input: typeof EmptySchema;
        output: typeof EmptySchema;
    };
}> = /*@__PURE__*/ serviceDesc(file_fixture_v1_multi, 1);
