// @generated by protoc-gen-es v2.16.0 with parameter "target=ts,import_extension=.ts,erasable_syntax=true"
// @generated from file fixture/v1/options.proto (package fixture.v1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file fixture/v1/options.proto.
 */
export const file_fixture_v1_options: GenFile =
    /*@__PURE__*/
    fileDesc("ChhmaXh0dXJlL3YxL29wdGlvbnMucHJvdG8SCmZpeHR1cmUudjE6NgoFYXVkaXQSHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxjRhgMgASgJUgVhdWRpdGIGcHJvdG8z", [
        file_google_protobuf_descriptor,
    ]);

/**
 * @generated from extension: string audit = 50001;
 */
export const audit: GenExtension<MethodOptions, string> = /*@__PURE__*/ extDesc(file_fixture_v1_options, 0);
