// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.ts"
// @generated from file streaming/v1/streaming.proto (package streaming.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file streaming/v1/streaming.proto.
 */
export const file_streaming_v1_streaming: GenFile =
    /*@__PURE__*/
    fileDesc(
        "ChxzdHJlYW1pbmcvdjEvc3RyZWFtaW5nLnByb3RvEgxzdHJlYW1pbmcudjEiJwoESXRlbRINCgV2YWx1ZRgBIAEoCRIQCghzZXF1ZW5jZRgCIAEoBSIWCgVDb3VudBINCgV0b3RhbBgBIAEoBTLfAQoQU3RyZWFtaW5nU2VydmljZRIuCgRFY2hvEhIuc3RyZWFtaW5nLnYxLkl0ZW0aEi5zdHJlYW1pbmcudjEuSXRlbRIyCgZTZXJ2ZXISEi5zdHJlYW1pbmcudjEuSXRlbRoSLnN0cmVhbWluZy52MS5JdGVtMAESMwoGQ2xpZW50EhIuc3RyZWFtaW5nLnYxLkl0ZW0aEy5zdHJlYW1pbmcudjEuQ291bnQoARIyCgRCaWRpEhIuc3RyZWFtaW5nLnYxLkl0ZW0aEi5zdHJlYW1pbmcudjEuSXRlbSgBMAFiBnByb3RvMw",
    );

/**
 * @generated from message streaming.v1.Item
 */
export type Item = Message<"streaming.v1.Item"> & {
    /**
     * @generated from field: string value = 1;
     */
    value: string;

    /**
     * @generated from field: int32 sequence = 2;
     */
    sequence: number;
};

/**
 * Describes the message streaming.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> = /*@__PURE__*/ messageDesc(file_streaming_v1_streaming, 0);

/**
 * @generated from message streaming.v1.Count
 */
export type Count = Message<"streaming.v1.Count"> & {
    /**
     * @generated from field: int32 total = 1;
     */
    total: number;
};

/**
 * Describes the message streaming.v1.Count.
 * Use `create(CountSchema)` to create a new message.
 */
export const CountSchema: GenMessage<Count> = /*@__PURE__*/ messageDesc(file_streaming_v1_streaming, 1);

/**
 * StreamingService — fixture for in-process transport streaming parity tests.
 *
 * @generated from service streaming.v1.StreamingService
 */
export const StreamingService: GenService<{
    /**
     * Unary echo.
     *
     * @generated from rpc streaming.v1.StreamingService.Echo
     */
    echo: {
        methodKind: "unary";
        input: typeof ItemSchema;
        output: typeof ItemSchema;
    };
    /**
     * Server-streaming: yields N items derived from request.
     *
     * @generated from rpc streaming.v1.StreamingService.Server
     */
    server: {
        methodKind: "server_streaming";
        input: typeof ItemSchema;
        output: typeof ItemSchema;
    };
    /**
     * Client-streaming: aggregates N input items into a count.
     *
     * @generated from rpc streaming.v1.StreamingService.Client
     */
    client: {
        methodKind: "client_streaming";
        input: typeof ItemSchema;
        output: typeof CountSchema;
    };
    /**
     * Bidi-streaming: echoes each received item back.
     *
     * @generated from rpc streaming.v1.StreamingService.Bidi
     */
    bidi: {
        methodKind: "bidi_streaming";
        input: typeof ItemSchema;
        output: typeof ItemSchema;
    };
}> = /*@__PURE__*/ serviceDesc(file_streaming_v1_streaming, 0);
