/**
 * Pure base transform for `connectum init`.
 *
 * Takes the file map of the fetched `getting-started` base plus the resolved
 * {@link ScaffoldConfig} and produces the final project file map. Pure (no I/O) so
 * it is fully unit-testable against a local fixture without any network.
 *
 * Base-level responsibilities (OpenSpec change cli-scaffolding, tasks 1.1/1.2/1.5/1.6):
 * - de-monorepo (drop `pnpm-workspace.yaml` / `.pnpmfile.cjs`);
 * - rewrite `package.json` (name, engines, scripts + lifecycle-fix, devDeps) for the
 *   chosen runtime / package-manager / node-exec model;
 * - regenerate the e2e test to use the public in-process `createLocalClient` (D-7).
 *
 * Module composition (events/otel/auth/...) layers on top of this in Phase 2.
 *
 * @module scaffold/transform
 */

import { generateIndex, generateServer } from "./serverGen.ts";
import type { NodeExec, PackageManager, Runtime, ScaffoldConfig } from "./types.ts";
import { nodeEngineFloor } from "./types.ts";

/** Files that are monorepo-only plumbing and never belong in a standalone project. */
const MONOREPO_ONLY = new Set(["pnpm-workspace.yaml", ".pnpmfile.cjs"]);

/** Path of the base sample's e2e test, regenerated by this transform. */
const E2E_TEST_PATH = "tests/e2e/e2e.test.ts";

/**
 * The scaffolded project's `scripts` block. A concrete type (not a `Record`) so the
 * absence of pnpm `pre*` hooks is structural — the lifecycle-fix lives inside
 * `typecheck`/`test`/`start`, not in a hook that silently no-ops.
 */
export interface ProjectScripts {
    "buf:generate": string;
    "buf:lint": string;
    "build:proto": string;
    typecheck: string;
    start: string;
    dev: string;
    test: string;
}

/**
 * Build the runtime/PM/node-exec-specific `scripts` block, with the lifecycle-fix
 * (`buf generate &&` prefixed onto `typecheck`/`test`/`start`) baked in and the
 * codegen alias kept package-manager-independent (`buf generate`, never `pnpm run …`).
 */
export function buildScripts(config: ScaffoldConfig): ProjectScripts {
    const common = {
        "buf:generate": "buf generate",
        "buf:lint": "buf lint",
        "build:proto": "buf generate",
        typecheck: "buf generate && tsc --noEmit",
    };

    if (config.runtime === "bun") {
        return {
            ...common,
            start: "buf generate && bun src/index.ts",
            dev: "bun --watch src/index.ts",
            test: "buf generate && bun test tests/",
        };
    }

    // Node
    const start = config.nodeExec === "tsx" ? "buf generate && tsx src/index.ts" : "buf generate && node src/index.ts";
    const dev = config.nodeExec === "tsx" ? "tsx watch src/index.ts" : "node --watch src/index.ts";
    // Under the tsx model (Node 22) `node --test` cannot strip `.ts`, so load tsx.
    const test = config.nodeExec === "tsx" ? "buf generate && node --import tsx --test tests/**/*.test.ts" : "buf generate && node --test tests/**/*.test.ts";
    return { ...common, start, dev, test };
}

/**
 * Build the `devDependencies` block for the scaffolded project.
 *
 * Keeps the codegen toolchain (`@bufbuild/buf`, `@bufbuild/protoc-gen-es`,
 * `typescript`, `@types/node`), adds `@connectum/testing` (for the in-process
 * `createLocalClient` e2e test, D-7), adds `tsx` only under the Node tsx model, and
 * drops `@connectrpc/connect-node` (unused now that the e2e test is in-process).
 */
export function buildDevDeps(existing: Record<string, string>, config: ScaffoldConfig, connectumVersion: string): Record<string, string> {
    const keep = ["@bufbuild/buf", "@bufbuild/protoc-gen-es", "@types/node", "typescript"];
    const devDeps: Record<string, string> = {};
    for (const key of keep) {
        if (existing[key]) {
            devDeps[key] = existing[key];
        }
    }
    devDeps["@connectum/testing"] = connectumVersion;
    if (config.runtime === "node" && config.nodeExec === "tsx") {
        devDeps.tsx = existing.tsx ?? "^4.21.0";
    }
    // Sort keys for a stable, diff-friendly package.json.
    return Object.fromEntries(Object.entries(devDeps).sort(([a], [b]) => (a < b ? -1 : 1)));
}

/**
 * Rewrite the base `package.json` for the target project.
 */
export function transformPackageJson(raw: string, config: ScaffoldConfig): string {
    const pkg = JSON.parse(raw) as Record<string, unknown> & {
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
    };

    pkg.name = config.name;
    delete pkg.private;
    pkg.description = `A Connectum gRPC/ConnectRPC service (${config.name})`;
    pkg.engines = config.runtime === "bun" ? { node: ">=22.13.0" } : { node: nodeEngineFloor(config.nodeExec) };

    // Version to pin @connectum/testing to: match the slice already used by the base
    // (keep the whole @connectum/* stack on one minor — see reference_examples_connectum_slice).
    const connectumVersion = pkg.dependencies?.["@connectum/core"] ?? "^1.0.0";

    // Additive module runtime deps (kept on the same @connectum slice, then sorted).
    if (config.modules.otel && pkg.dependencies) {
        pkg.dependencies = Object.fromEntries(Object.entries({ ...pkg.dependencies, "@connectum/otel": connectumVersion }).sort(([a], [b]) => (a < b ? -1 : 1)));
    }

    pkg.scripts = buildScripts(config);
    pkg.devDependencies = buildDevDeps(pkg.devDependencies ?? {}, config, connectumVersion);

    return `${JSON.stringify(pkg, null, 2)}\n`;
}

/**
 * Generate the in-process e2e test for the sample Greeter service (D-7). The test
 * body is identical across runtimes; only the test-runner import differs
 * (`node:test` on Node, `bun:test` on Bun, matching the chosen `test` script).
 */
export function generateGreeterE2eTest(runtime: Runtime): string {
    const runnerImport = runtime === "bun" ? 'import { describe, it } from "bun:test";' : 'import { describe, it } from "node:test";';
    return `/**
 * End-to-end test for the sample Greeter service.
 *
 * Uses @connectum/testing's in-process \`createLocalClient\` — no socket is opened,
 * so the same test runs identically on Node and Bun.
 */

import assert from "node:assert/strict";
${runnerImport}
import { createServer } from "@connectum/core";
import { createLocalClient } from "@connectum/testing";
import { GreeterService } from "#gen/greeter/v1/greeter_pb.ts";
import { greeterService } from "#services/greeterService.ts";

describe("GreeterService", () => {
    const server = createServer({ services: [greeterService] });
    const client = createLocalClient(server, GreeterService);

    it("sayHello returns a greeting", async () => {
        const res = await client.sayHello({ name: "Ada" });
        assert.equal(res.message, "Hello, Ada!");
    });

    it("sayGoodbye returns a farewell", async () => {
        const res = await client.sayGoodbye({ name: "Ada" });
        assert.equal(res.message, "Goodbye, Ada!");
    });
});
`;
}

/**
 * Transform the fetched base file map into the final project file map.
 *
 * @param files - The fetched `getting-started` base (relative path -> content)
 * @param config - Resolved scaffolding configuration
 * @returns The final project file map, ready for {@link emitFiles}
 */
export function transformBase(files: ReadonlyMap<string, string>, config: ScaffoldConfig): Map<string, string> {
    const out = new Map<string, string>();

    for (const [relPath, content] of files) {
        if (MONOREPO_ONLY.has(relPath)) {
            continue;
        }
        if (relPath === "README.md") {
            // README is regenerated below (project-specific).
            continue;
        }
        if (relPath === E2E_TEST_PATH) {
            // Regenerated with the in-process createLocalClient (D-7).
            continue;
        }
        if (relPath === "src/server.ts" || relPath === "src/index.ts") {
            // Regenerated as the composition root from the module set (D-2/D-3).
            continue;
        }
        if (relPath === "package.json") {
            out.set(relPath, transformPackageJson(content, config));
            continue;
        }
        out.set(relPath, content);
    }

    out.set("src/server.ts", generateServer(config));
    out.set("src/index.ts", generateIndex(config));
    out.set(E2E_TEST_PATH, generateGreeterE2eTest(config.runtime));
    out.set("README.md", generateReadme(config));

    // A standalone pnpm project still needs to approve @bufbuild/buf's postinstall
    // (the buf binary download); under pnpm 11 that setting lives in
    // `pnpm-workspace.yaml` (the package.json `pnpm.*` field is no longer read).
    // Without it pnpm blocks the build and `buf generate` cannot run. npm runs
    // postinstall by default, so no file is needed there.
    if (config.packageManager === "pnpm") {
        out.set("pnpm-workspace.yaml", "onlyBuiltDependencies:\n  - '@bufbuild/buf'\n  - esbuild\n");
    }

    return out;
}

/**
 * Generate a short project README with the correct run commands for the chosen
 * runtime and package manager.
 */
export function generateReadme(config: ScaffoldConfig): string {
    const pm = config.packageManager;
    const run = (script: string): string => `${pm} run ${script}`;
    const runtimeNote =
        config.runtime === "bun"
            ? "Runs on **Bun**."
            : config.nodeExec === "tsx"
              ? "Runs on **Node.js >= 22.13.0** via `tsx`."
              : "Runs on **Node.js >= 25.2.0** (native TypeScript execution).";
    return `# ${config.name}

A Connectum gRPC/ConnectRPC service scaffolded with \`connectum init\`.

${runtimeNote}

## Getting started

\`\`\`bash
${pm} install
${run("start")}
\`\`\`

\`buf generate\` runs automatically before \`start\`, \`test\`, and \`typecheck\`, so the
generated code under \`gen/\` is always up to date.

## Commands

- \`${run("start")}\` — start the server
- \`${run("dev")}\` — start in watch mode
- \`${run("test")}\` — run tests
- \`${run("typecheck")}\` — type-check
- \`${run("buf:lint")}\` — lint proto files

## Next steps

Replace the sample \`Greeter\` service under \`proto/\` and \`src/services/\` with your
own contract, then run \`buf generate\`.
`;
}

// Re-export the config value types used by transform consumers.
export type { NodeExec, PackageManager, Runtime, ScaffoldConfig };
