// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.ts"
// @generated from file echo/v1/echo.proto (package echo.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file echo/v1/echo.proto.
 */
export const file_echo_v1_echo: GenFile =
    /*@__PURE__*/
    fileDesc(
        "ChJlY2hvL3YxL2VjaG8ucHJvdG8SB2VjaG8udjEiHgoLRWNob1JlcXVlc3QSDwoHbWVzc2FnZRgBIAEoCSIyCgxFY2hvUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCRIRCgl0aW1lc3RhbXAYAiABKAMywwEKC0VjaG9TZXJ2aWNlEjUKBEVjaG8SFC5lY2hvLnYxLkVjaG9SZXF1ZXN0GhUuZWNoby52MS5FY2hvUmVzcG9uc2UiABI7CgpTZWN1cmVFY2hvEhQuZWNoby52MS5FY2hvUmVxdWVzdBoVLmVjaG8udjEuRWNob1Jlc3BvbnNlIgASQAoPUmF0ZUxpbWl0ZWRFY2hvEhQuZWNoby52MS5FY2hvUmVxdWVzdBoVLmVjaG8udjEuRWNob1Jlc3BvbnNlIgBiBnByb3RvMw",
    );

/**
 * @generated from message echo.v1.EchoRequest
 */
export type EchoRequest = Message<"echo.v1.EchoRequest"> & {
    /**
     * @generated from field: string message = 1;
     */
    message: string;
};

/**
 * Describes the message echo.v1.EchoRequest.
 */
export const EchoRequestSchema: GenMessage<EchoRequest> = /*@__PURE__*/ messageDesc(file_echo_v1_echo, 0);

/**
 * @generated from message echo.v1.EchoResponse
 */
export type EchoResponse = Message<"echo.v1.EchoResponse"> & {
    /**
     * @generated from field: string message = 1;
     */
    message: string;

    /**
     * @generated from field: int64 timestamp = 2;
     */
    timestamp: bigint;
};

/**
 * Describes the message echo.v1.EchoResponse.
 */
export const EchoResponseSchema: GenMessage<EchoResponse> = /*@__PURE__*/ messageDesc(file_echo_v1_echo, 1);

/**
 * EchoService — fixture for in-process transport tests.
 *
 * @generated from service echo.v1.EchoService
 */
export const EchoService: GenService<{
    /**
     * @generated from rpc echo.v1.EchoService.Echo
     */
    echo: {
        methodKind: "unary";
        input: typeof EchoRequestSchema;
        output: typeof EchoResponseSchema;
    };
    /**
     * @generated from rpc echo.v1.EchoService.SecureEcho
     */
    secureEcho: {
        methodKind: "unary";
        input: typeof EchoRequestSchema;
        output: typeof EchoResponseSchema;
    };
    /**
     * @generated from rpc echo.v1.EchoService.RateLimitedEcho
     */
    rateLimitedEcho: {
        methodKind: "unary";
        input: typeof EchoRequestSchema;
        output: typeof EchoResponseSchema;
    };
}> = /*@__PURE__*/ serviceDesc(file_echo_v1_echo, 0);
