name: Buf Proto

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/auth/proto/**"
      - "packages/auth/buf.yaml"
      - "packages/events/proto/**"
      - "packages/events/buf.yaml"
      - ".github/workflows/buf.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint & Breaking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [auth, events]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: bufbuild/buf-action@v1
        with:
          input: packages/${{ matrix.package }}
          push: false
